### ISSUE TITLE
Could not open library: libduckdb.so

### ISSUE THREAD

**Issue by Tuanm** [littledivy/duckdb#2]
I'm tryna use your [duckdb](https://deno.land/x/duckdb@0.1.1/mod.ts) for my very simple Deno project, but getting stuck on these:
```
error: Uncaught (in promise) Error: Could not open library: Could not open library: libduckdb.so: cannot open shared object file: No such file or directory
  return Deno.dlopen(file, symbols);
              ^
    at new DynamicLibrary (ext:deno_ffi/00_ffi.js:440:46)
    at Object.dlopen (ext:deno_ffi/00_ffi.js:577:10)
    at prepare (https://deno.land/x/plug@0.5.2/plug.ts:117:15)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async https://deno.land/x/duckdb@0.1.1/lib.js:47:
```

I've been reloading the dependencies:
```
$ deno install -r https://deno.land/x/duckdb@0.1.1/mod.ts
✅ Successfully installed duckdb
/home/vi/.deno/bin/duckdb
```
but it still doesn't work.

ICYMI, I'm using Deno 1.33.4 on my Ubuntu 18.04 (WSL2):
```
$ deno --version 
deno 1.33.4 (release, x86_64-unknown-linux-gnu)
v8 11.4.183.2
typescript 5.0.4
```

**Comment by gilesdring** [comment]
I had to download the C/C++ installer for DuckDB from here, https://duckdb.org/docs/installation/index

Then extract the .so file from within the package zip, and place that on the library path. This may be something like /usr/local/lib. I also had some success exporting LD_LIBRARY_PATH to a known directory and placing the library file there.

Hope this helps!

**Comment by Tuanm** [comment]
> I had to download the C/C++ installer for DuckDB from here, https://duckdb.org/docs/installation/index
> 
> Then extract the .so file from within the package zip, and place that on the library path. This may be something like /usr/local/lib. I also had some success exporting LD_LIBRARY_PATH to a known directory and placing the library file there.
> 
> Hope this helps!

Thank you, I've switched to a real Linux environment (instead of using WSL2) and didn't face this issue then. Anyway, let me check your approach in my old WSL2. :D

**Comment by gilesdring** [comment]
On second look, this is still a problem - looks like the use of the plug library is failing. I'll have a further dig.

**Comment by ghost** [comment]
@gilesdring Any success?

I am facing the same issue. Running the example from the README:
```bash
$ deno run --allow-ffi --unstable-ffi -A duckdb-deno.ts
error: Uncaught (in promise) Error: Could not open library: Could not open library: libduckdb.so: cannot open shared object file: No such file or directory
  return Deno.dlopen<S>(await download(options), symbols as any);
              ^
    at new DynamicLibrary (ext:deno_ffi/00_ffi.js:454:42)
    at Object.dlopen (ext:deno_ffi/00_ffi.js:558:10)
    at dlopen (https://jsr.io/@divy/plug/1.0.3/mod.ts:155:15)
    at eventLoopTick (ext:core/01_core.js:168:7)
    at async https://jsr.io/@divy/duckdb/0.2.1/lib.js:41:27
```
