### ISSUE TITLE
Unable to load `libduckdb.dylib` on MacOS

### ISSUE THREAD

**Issue by rgbkrk** [littledivy/duckdb#5]
In:

```
import { open } from "https://deno.land/x/duckdb/mod.ts";
```

Out:

```
Error: Could not open library: Could not open library: dlopen(/Users/kai/Library/Caches/deno/plug/https/github.com/ae1f893a6408857d578f70bdcfb9be0dfceb8a78249f334568cdbc049dd8a3e2.dylib, 0x0005): Library not loaded: /opt/homebrew/opt/duckdb/lib/libduckdb.dylib
  Referenced from: <16F8C5EE-2AF3-391B-A6E5-9F5B58282662> /Users/kai/Library/Caches/deno/plug/https/github.com/ae1f893a6408857d578f70bdcfb9be0dfceb8a78249f334568cdbc049dd8a3e2.dylib
  Reason: tried: '/opt/homebrew/opt/duckdb/lib/libduckdb.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/duckdb/lib/libduckdb.dylib' (no such file), '/opt/homebrew/opt/duckdb/lib/libduckdb.dylib' (no such file), '/usr/local/lib/libduckdb.dylib' (no such file), '/usr/lib/libduckdb.dylib' (no such file, not in dyld cache)
    at new DynamicLibrary (ext:deno_ffi/00_ffi.js:440:46)
    at Object.dlopen (ext:deno_ffi/00_ffi.js:577:10)
    at prepare (https://deno.land/x/plug@0.5.2/plug.ts:117:15)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async https://deno.land/x/duckdb@0.1.1/lib.js:47:27: 
```

**Comment by johnoscott** [comment]
I tried to import in a Jupyter notebook (using deno kernel) and got this response :

```
Download https://github.com/littledivy/duckdb/releases/download/0.1.0/libduckdb_aarch64.dylib
```

What do i do with this file ?
