### ISSUE TITLE
Release v0.2.1

### ISSUE THREAD

**Issue by ghost** [littledivy/duckdb#8]
Just found your amazing little project and wanted to make use of it, however:
```
error: Uncaught (in promise) TypeError: Deno.dlopen is not a function
  return Deno.dlopen(file, symbols);
              ^
    at prepare (https://deno.land/x/plug@0.5.2/plug.ts:117:15)
    at eventLoopTick (ext:core/01_core.js:168:7)
    at async https://deno.land/x/duckdb@0.1.1/lib.js:47:27
```

I can see 2 issues for use:
1. the official latest version in Deno Land is still 0.1.1: https://deno.land/x/duckdb
2. there is no release made in GitHub, so we can not work around that by fetching from GH instead

Is there some way to import in Deno I don't know about to make use of the newest version?

**Comment by ghost** [comment]
...I am so stupid...

Since recent commit messages have indicated, it is not published in deno.land, but in JSR instead:
* https://jsr.io/@divy/duckdb
